spring:
  profiles:
    active: dev

  datasource:
    druid:
      driver-class-name: ${jd.datasource.classname}
      username: ${jd.datasource.username}
      password: ${jd.datasource.password}
      url: jdbc:mysql://${jd.datasource.host}:${jd.datasource.port}/${jd.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

  type-aliases-package: com.wolfhouse.journeydaily.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0



logging:
  level:
    com.wolfhouse.journeydaily: debug
server:
  address: 0.0.0.0
